reference_genome: hs37d5.fa
bamlist_file: /ERROR_RATE_ESTIMATION_PIPELINE/bamlist_file.txt
bamfile_extension: .dedupa.rg.sorted.bam
gene_bedfile: /ERROR_RATE_ESTIMATION_PIPELINE/AKT1.bed
gene_name: AKT1
snakedir: /ERROR_RATE_ESTIMATION_PIPELINE



# resources:
resources_mb:
  rule_pileup: 100000
  rule_process_pileup: 100000
  rule_estimate_error_rate: 100000